from ciphers.utils.types import LetterFrequencyDict

# According to https://de.wikipedia.org/wiki/Buchstabenh%C3%A4ufigkeit
GERMAN_LETTER_FREQUENCIES: LetterFrequencyDict = {
    "E": 0.1740,
    "N": 0.0978,
    "I": 0.0755,
    "S": 0.0727,
    "R": 0.0700,
    "A": 0.0651,
    "T": 0.0615,
    "D": 0.0508,
    "H": 0.0476,
    "U": 0.0435,
    "L": 0.0344,
    "C": 0.0306,
    "G": 0.0301,
    "M": 0.0253,
    "O": 0.0251,
    "B": 0.0189,
    "W": 0.0189,
    "F": 0.0166,
    "K": 0.0121,
    "Z": 0.0113,
    "P": 0.0079,
    "V": 0.0067,
    "SS": 0.0031,
    "J": 0.0027,
    "Y": 0.0004,
    "X": 0.0003,
    "Q": 0.0002,
}

# According to https://en.wikipedia.org/wiki/Index_of_coincidence
GERMAN_INDEX_OF_COINCIDENCE = 2.05

# According to https://de.wikipedia.org/wiki/Liste_der_h%C3%A4ufigsten_W%C3%B6rter_der_deutschen_Sprache
GERMAN_MOST_COMMON_WORDS = [
    "die",
    "der",
    "und",
    "in",
    "zu",
    "den",
    "das",
    "nicht",
    "von",
    "sie",
    "ist",
    "des",
    "sich",
    "mit",
    "dem",
    "dass",
    "er",
    "es",
    "ein",
    "ich",
    "auf",
    "so",
    "eine",
    "auch",
    "als",
    "an",
    "nach",
    "wie",
    "im",
    "für",
    "man",
    "aber",
    "aus",
    "durch",
    "wenn",
    "nur",
    "war",
    "noch",
    "werden",
    "bei",
    "hat",
    "wir",
    "was",
    "wird",
    "sein",
    "einen",
    "welche",
    "sind",
    "oder",
    "zur",
    "um",
    "haben",
    "einer",
    "mir",
    "über",
    "ihm",
    "diese",
    "einem",
    "ihr",
    "uns",
    "da",
    "zum",
    "kann",
    "doch",
    "vor",
    "dieser",
    "mich",
    "ihn",
    "du",
    "hatte",
    "seine",
    "mehr",
    "am",
    "denn",
    "nun",
    "unter",
    "sehr",
    "selbst",
    "schon",
    "hier",
    "bis",
    "habe",
    "ihre",
    "dann",
    "ihnen",
    "seiner",
    "alle",
    "wieder",
    "meine",
    "Zeit",
    "gegen",
    "vom",
    "ganz",
    "einzelnen",
    "wo",
    "muss",
    "ohne",
    "eines",
    "können",
    "sei",
    "ja",
    "wurde",
    "jetzt",
    "immer",
    "seinen",
    "wohl",
    "dieses",
    "ihren",
    "würde",
    "diesen",
    "sondern",
    "weil",
    "welcher",
    "nichts",
    "diesem",
    "alles",
    "waren",
    "will",
    "Herr",
    "viel",
    "mein",
    "also",
    "soll",
    "worden",
    "lassen",
    "dies",
    "machen",
    "ihrer",
    "weiter",
    "Leben",
    "recht",
    "etwas",
    "keine",
    "seinem",
    "ob",
    "dir",
    "allen",
    "großen",
    "Jahre",
    "Weise",
    "müssen",
    "welches",
    "wäre",
    "erst",
    "einmal",
    "Mann",
    "hätte",
    "zwei",
    "dich",
    "allein",
    "Herren",
    "während",
    "Paragraph",
    "anders",
    "Liebe",
    "kein",
    "damit",
    "gar",
    "Hand",
    "Herrn",
    "euch",
    "sollte",
    "konnte",
    "ersten",
    "deren",
    "zwischen",
    "wollen",
    "denen",
    "dessen",
    "sagen",
    "bin",
    "Menschen",
    "gut",
    "darauf",
    "wurden",
    "weiß",
    "gewesen",
    "Seite",
    "bald",
    "weit",
    "große",
    "solche",
    "hatten",
    "eben",
    "andern",
    "beiden",
    "macht",
    "sehen",
    "ganze",
    "anderen",
    "lange",
    "wer",
    "ihrem",
    "zwar",
    "gemacht",
    "dort",
    "kommen",
    "Welt",
    "heute",
    "Frau",
    "werde",
    "derselben",
    "ganzen",
    "deutschen",
    "lässt",
    "vielleicht",
    "meiner",
]
